// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package sounds

import _ "embed"


//go:embed explosion.ogg
var Explosion_ogg string

//go:embed laser.ogg
var Laser_ogg string

//go:embed music.ogg
var Music_ogg string

