// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package fonts

import _ "embed"


//go:embed monogram.ttf
var Monogram_ttf []byte

