// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package src

import _ "embed"


//go:embed alien_1.png
var Alien_1_png []byte

//go:embed alien_2.png
var Alien_2_png []byte

//go:embed alien_3.png
var Alien_3_png []byte

//go:embed mystery.png
var Mystery_png []byte

//go:embed ships.png
var Ships_png []byte

//go:embed ships.xml
var Ships_xml string

//go:embed spaceship.png
var Spaceship_png []byte

